# Exercices numpy

Dans ces exercices, il faut privilégier les solutions Numpy, plutôt que de les recoder en python

In [1]:
import numpy as np

1. Créer et afficher un tableau numpy comprenant dans l'ordre les entiers de 10 à 59

In [2]:
numpy_array = np.arange(10, 60)
print(numpy_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


2. Créer un tableau x et l'inverser. Utiliser le slicing 

In [3]:
xx = numpy_array[::-1]
print(xx)

[59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35
 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


3. Créer un tableau 3*3 contenant les valeurs de 0 à 8

In [4]:
array33 = np.arange(9)
array33 = array33.reshape(3, 3)
print(array33)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Créer un tableau 10*10 avec des valeurs aléatoires et trouver le minimum et le maximum

In [5]:
array1010 = np.random.randint(100, size=100).reshape(10, 10)
print(array1010)
print(array1010.min())
print(array1010.max())

[[65 29  5 44 79 77 21 28 28 40]
 [25 81 76 11 77 78 59 79 84 65]
 [13 27 36 18 33 79 52 54 53 54]
 [26 35 24 94 79 59 14 69 97 79]
 [48 75 30 61 70 66  7  5 74 65]
 [22 93 40 40 71 35 25 46 53  6]
 [47 33 28 56 22 45 10 91 80 54]
 [43 42 51 76 96 54 10 22  9 87]
 [80 72 64 17 38 34 49  3 42 30]
 [53 38 96 63 18 74 64 13 85 16]]
3
97


6. Créer un tableau 2D avec des 1 sur les bords et des 0 à l'intérieur.  

In [42]:
array2D = np.full((5, 15), 0, dtype=int)
# Change Top
#array2D[[0,]] = 1
# Change Bottom
#array2D[[array2D.shape[0] - 1,]] = 1

# Change Top and Bottom
array2D[[0, array2D.shape[0] - 1]] = 1

# Change Left
array2D[:, 0] = 1

# Change Right
array2D[:, array2D.shape[1] - 1] = 1

print(array2D)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


7. Créer un tableau à 1 dimension et inverser tous les éléments compris entre 3 et 8 (inclus). Utiliser un tableau booléen comme masque.  

8. Créer un tableau de 19 valeurs décimales croissantes à pas égal entre 13.4 et 123.99 (inclus puis exclus). Utiliser np.linspace.  

9. Créer un tableau de 19 valeurs décimales aléatoires et remplacer le maximum par 0.   

10. Créer un tableau avec des valeurs aléatoires. Soustraire à chaque case sa moyenne. Utiliser le broadcasting. Vérifier que la moyenne est nulle

11. Créer un tableau 5*5 avec des valeurs aléatoires. Soustraire à chaque colonne sa moyenne. 

12. Créer un tableau de 10*2 avec des valeurs aléatoires représentant des coordonnées de points. 

- Trouver le tableau 10*10 qui consigne les distances entre chaque paire de points. Utiliser (au maximum) le broadcasting
- Relier chaque point à son voisin le plus proche
- Relier chaque point à ses 3 plus proches voisins

Reprendre le code suivant pour afficher les points

In [ ]:
ages = 2
x,y=np.histogram(ages)
x,y

1. Refaire les memsures précédentes en distingant les passagers ayant survécus des autres. Pour l'histogramme, faire apparaître 2 barres par tranche d'age. Utiliser plt.subplots et np.histogram
2. Y a t il un attribut (hormis survived) qui est plus significatif dans la séparation des survivants/non survivants